### ISSUE TITLE
AX7 Data Entities - OData Generator - Combined length of user strings used by the program exceeds allowed limit.

### ISSUE THREAD

**Issue by aherrick** [Microsoft/Dynamics-AX-Integration#17]
Using the following OData Metadata URL to wrap the Entities in Visual Studio:

https://usnconeboxax1aos.cloud.onebox.dynamics.com/data/$metadata

The OData Generator is able to successfully wrap the entities, however receiving the following error in VS:

`Error	CS8103	Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.	`

My guess is that the generated file is so big VS can't even handle it. I've attempting stripping out entities manually, but that doesn't seem ideal.

Thoughts on a work around?

**Comment by RaphaelTagliani** [comment]
Hi Andrew,

I ran into the same issue, and solved it... But I can't remember how! I searched in my revlog, nothing :(
This is indeed the client generated that is too large.

Maybe this can help :
- I use Visual studio 2015
- .Net 4.6.1
- I specified a namespace in the .tt file
...and I did not run into this issue since quite a long time.

The only post I found about this issue is not really helping :
http://stackoverflow.com/questions/37193372/c-sharp-combined-length-of-user-strings-used-by-the-program-exceeds-allowed-limi

Anyway, generating such a large client for integration scenarios where we need only a few entities is not a good solution. There has to be a way to filter the entities for which we want to generate the client. If you find a solution for that, I'm highly interrested. The solution probably lies in tweaking ODataClient.ttinclude, but I don't want to deep-dive into client code generation... I hope an OData guru can help you.

Another simple solution is not to rely on code generation, and to use an HTTP post/get and parse the results. This is less elegant and requires to check the code in case of upgrades, but it is much more efficient at the runtime (no need to load a lot of useless MBs in memory).

I hope you will find a solution soon...

**Comment by aherrick** [comment]
Hi Raphael,

Thanks for the awesome reply! I went ahead and moved the Client into its own Project and bumped up to 4.6.1... So far so good! 

I like the idea of using just raw HTTP calls... going to keep that in back pocket.

Also made a few small tweaks to the `ttinclude` to clean up some of the generation. See images below:

Only Entities I need:

![1](https://cloud.githubusercontent.com/assets/586671/21509906/e41e9db8-cc5b-11e6-9517-2df1a112d5fd.png)

Remove "AddTo" Methods:

![2](https://cloud.githubusercontent.com/assets/586671/21509907/e92f5b1c-cc5b-11e6-90ca-da24774517df.png)

Cheers!

**Comment by RaphaelTagliani** [comment]
Nice! Good work :)
I like your solution to prune some entities (Contains("LEX")), I will try to use it as well. I guess there will be some side effects if some entities are linked, but nothing a list of entities can't fix.

**Comment by batetech** [comment]
I've traced this back to this line in the ttinclude that is causing the "Combined length of user strings used by the program exceeds allowed limit" error for me during generation of Dynamics data entities: 
`private const string Edmx = @"<#= escapedEdmxString #>";`

My workaround was to change the ttinclude so the Edmx is a filename instead of the Edmx file contents as a string, then save the Edmx as a separate file which is treated as an embedded resource, and then update the CreateXMLReader method to take the resource name instead: 

 ```
private static global::System.Xml.XmlReader CreateXmlReader(string edmxFilePath)
            {
				//Get the EDMX contents from an embedded resource.
				var assembly = System.Reflection.Assembly.GetExecutingAssembly();
				string resourceName = assembly.GetName().Name + "." + edmxFilePath;
                return global::System.Xml.XmlReader.Create(assembly.GetManifestResourceStream(resourceName)); 
            }
```

**Comment by vishram2997** [comment]
> Hi Raphael,
> 
> Thanks for the awesome reply! I went ahead and moved the Client into its own Project and bumped up to 4.6.1... So far so good!
> 
> I like the idea of using just raw HTTP calls... going to keep that in back pocket.
> 
> Also made a few small tweaks to the `ttinclude` to clean up some of the generation. See images below:
> 
> Only Entities I need:
> 
> ![1](https://cloud.githubusercontent.com/assets/586671/21509906/e41e9db8-cc5b-11e6-9517-2df1a112d5fd.png)
> 
> Remove "AddTo" Methods:
> 
> ![2](https://cloud.githubusercontent.com/assets/586671/21509907/e92f5b1c-cc5b-11e6-90ca-da24774517df.png)
> 
> Cheers!

I am getting error after above changes.
Compiling transformation: The name 'edmNavigationSourceList' does not exist in the current context

**Comment by rajendrapol05** [comment]
Refer below URL it's work for me.
https://github.com/OData/odata.net/issues/1220
Regards
Rajendra Pol

**Comment by ranandk** [comment]
Hi, Is there any soultion for the problem? It is still happening with the visual studion 2015.. Any suggestions would be appreciated...
